# Generated by Django 4.1.1 on 2022-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created date"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="Date of birth"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Phone number"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated date"),
        ),
    ]
