# Generated by Django 4.1.1 on 2022-10-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contacts_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="is_auto_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of birth"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone number"
            ),
        ),
    ]
